# Function Generation for the Training of λ-Nets

## 0: Preparation

In [ ]:
##############DO NOT CHANGE###################

# Importing own helper library
import sys
sys.path.insert(0,'../_baselib')
import general_helper as gh
import polynom_helper as ph

# Third-party imports
from tqdm.notebook import tqdm
import numpy as np
import pandas as pd
from joblib import Parallel, delayed 
# sympy for Polynomial support
from sympy.polys import monomials
from sympy.polys.orderings import monomial_key
from sympy import symbols

# Static settings & directory preparation
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
    
gh.create_dir('./data')
subdirectories = ['parameters', 'plotting', 'saved_polynomial_lists', 'results', 'saved_models', 'weights', 'weights_training']
for dir_ in subdirectories:
    gh.create_dir('./data/' + dir_)

## 1: Specification of Experiment Settings

In [2]:
# parse settings from a configuration file ('config.ini')

config_path = 'config.ini'

try:
    config = gh.parse_config(config_path)
    locals().update(config)
    
except Exception as e:
    print('Parsing not possible due to Exception:')
    print(e)
    print('\nContinue with manual specification.')

In [3]:
# manual override of config and/or additional variable specification

#d = 3  
#n = 4
#sparsity = 0.0
#a_max = 10 
#a_min = -10
#a_step = 0.1
#x_max = 1 
#x_min = -1
#x_step = 0.01
#lambda_dataset_size = 100 
#interpretation_dataset_size = 5000
#same_training_all_polynomials = True

#n_jobs = 10

# ------------------------------------------------------------------

In [4]:
##############DO NOT CHANGE###################

# set derived attributes
variables = 'abcdefghijklmnopqrstuvwxyz'[:n]
if same_training_all_polynomials: training_string = '_same'
else: training_string = '_diverse'

In [5]:
# inspect most important settings
print('Variables: ' + str(n) + ' (' + variables + ')')
print('Degree: ' + str(d))
print('Sparsity: ' + str(sparsity*100) + '%') 
print('Lambda-Net Dataset Size: ' + str(lambda_dataset_size))
print('I-Net Dataset Size: ' + str(interpretation_dataset_size))
      
print('Coefficient Range: ' + '[' + str(a_min) + ', ' + str(a_max) + ']')
print('Variable Range: ' + '[' + str(x_min) + ', ' + str(x_max) + ']')

Variables: 4 (abcd)
Degree: 3
Sparsity: 0.0%
Lambda-Net Dataset Size: 100
I-Net Dataset Size: 5000
Coefficient Range: [-10.0, 10.0]
Variable Range: [-1.0, 1.0]


## 2: Generation of all possible Monomials

In [6]:
polys_symbols = symbols(list(variables))
polys_monomials = sorted(monomials.itermonomials(variables = polys_symbols, max_degrees = d, min_degrees = None), 
                                      reverse = True, key = monomial_key('lex', polys_symbols))
monomials_count = monomials.monomial_count(n, d)

tuples_monomials = [ph.monomial_to_power_tuple(mon, polys_symbols) for mon in polys_monomials]

print('List length: ' + str(len(polys_monomials)))
print('Number of monomials in a polynomial with ' + str(n) + ' variables and degree ' + str(d) + ': ' + str(monomials_count))
print(polys_monomials)
print(tuples_monomials)

List length: 35
Number of monomials in a polynomial with 4 variables and degree 3: 35
[a**3, a**2*b, a**2*c, a**2*d, a**2, a*b**2, a*b*c, a*b*d, a*b, a*c**2, a*c*d, a*c, a*d**2, a*d, a, b**3, b**2*c, b**2*d, b**2, b*c**2, b*c*d, b*c, b*d**2, b*d, b, c**3, c**2*d, c**2, c*d**2, c*d, c, d**3, d**2, d, 1]
[(3, 0, 0, 0), (2, 1, 0, 0), (2, 0, 1, 0), (2, 0, 0, 1), (2, 0, 0, 0), (1, 2, 0, 0), (1, 1, 1, 0), (1, 1, 0, 1), (1, 1, 0, 0), (1, 0, 2, 0), (1, 0, 1, 1), (1, 0, 1, 0), (1, 0, 0, 2), (1, 0, 0, 1), (1, 0, 0, 0), (0, 3, 0, 0), (0, 2, 1, 0), (0, 2, 0, 1), (0, 2, 0, 0), (0, 1, 2, 0), (0, 1, 1, 1), (0, 1, 1, 0), (0, 1, 0, 2), (0, 1, 0, 1), (0, 1, 0, 0), (0, 0, 3, 0), (0, 0, 2, 1), (0, 0, 2, 0), (0, 0, 1, 2), (0, 0, 1, 1), (0, 0, 1, 0), (0, 0, 0, 3), (0, 0, 0, 2), (0, 0, 0, 1), (0, 0, 0, 0)]


## 3: Generation of randomly chosen Polynomials

In [7]:
all_coefficients = np.random.choice(np.arange(a_min, a_max + a_step, a_step), 
                                       size=(interpretation_dataset_size, monomials_count), replace=True)
all_coefficients = np.round(all_coefficients, int(-np.log10(a_step)))
    
# Sparsity
if sparsity > 0:
    # add sparsity --> set random coefficients to 0 (#coefficients = #monomials - sparsity)
    for coeffs in tqdm(all_coefficients):
        sparsity_indices = np.random.choice(monomials_count + 1, floor(monomials_count * sparsity), replace=False)
        for sparsity_index in sparsity_indices:                            
            coeffs[sparsity_index] = 0

### 3.1: Polynomials as 'sympy.polys.polytools.Poly' objects

In [8]:
polynomials_poly = [ph.build_Poly(coeffs, tuples_monomials, polys_symbols) for coeffs in all_coefficients]

# inspection of first polynomial
polynomials_poly [0]

Poly(0.2*a**3 + 7.9*a**2*b - 0.8*a**2*c - 8.6*a**2*d + 0.6*a**2 - 2.9*a*b**2 + 8.8*a*b*c - 8.0*a*b*d + 0.2*a*b + 2.1*a*c**2 - 2.6*a*c*d - 1.3*a*c + 1.6*a*d**2 - 0.1*a*d + 0.3*a + 5.1*b**3 + 3.0*b**2*c + 4.9*b**2*d - 4.8*b**2 - 9.9*b*c**2 - 1.3*b*c*d + 5.7*b*c - 6.3*b*d**2 + 2.9*b*d + 9.1*b + 8.7*c**3 - 8.0*c**2*d + 6.0*c**2 - 4.3*c*d**2 - 7.9*c*d - 1.2*c - 5.2*d**3 - 4.2*d**2 + 6.9*d + 8.7, a, b, c, d, domain='RR')

### 3.2: Polynomials as coefficient rows and monomials in dataframe

In [9]:
polynomials_df = pd.DataFrame(data=all_coefficients, columns=polys_monomials)

# data inspection
print(len(polys_monomials))
print(polynomials_df.shape)
polynomials_df.head()

35
(5000, 35)


a**3  a**2*b  a**2*c  a**2*d  a**2  a*b**2  a*b*c  a*b*d  a*b  a*c**2  ...  \
0   0.2     7.9    -0.8    -8.6   0.6    -2.9    8.8   -8.0  0.2     2.1  ...   
1  -8.6     8.9     8.9     7.4   8.9    -5.0    0.7   -4.6 -3.7     3.0  ...   
2  -5.1     0.3     3.1    -9.9   3.3    -4.7    0.5   -9.7 -4.7     9.0  ...   
3  -9.2    -1.3     2.8     3.5  -3.8     3.8   -2.0    3.5  6.2     6.2  ...   
4   4.1     0.2    -7.4     3.6  -8.6    -1.1   -5.9    2.3  7.8    -3.8  ...   

   c**3  c**2*d  c**2  c*d**2  c*d    c  d**3  d**2     d    1  
0   8.7    -8.0   6.0    -4.3 -7.9 -1.2  -5.2  -4.2   6.9  8.7  
1  -0.9     1.0   8.7     9.8  7.1 -9.3   7.4  -6.6  -2.0  6.3  
2   5.3     8.7   2.3    -6.0  5.6 -8.6  -5.6  -3.6  -1.2 -3.0  
3  -0.2     7.1   0.3    -6.6  9.2 -0.0   7.4   3.0 -10.0 -9.6  
4  -3.5     6.9  -5.6    -3.9  8.4  3.3  -7.3  -7.3   0.7 -5.7  

[5 rows x 35 columns]

## 4: Precompute Polynomials with Input Values

In [10]:
# create input values

if same_training_all_polynomials:
        
    x_values = np.random.choice(np.arange(x_min, x_max + x_step, x_step), 
                                size=(lambda_dataset_size, n), replace=True)
    x_values = np.round(x_values, int(-np.log10(x_step)))

# inspection
print('Number of points: ' + str(len(x_values)))
print('Number of values per point: ' + str(len(x_values[0])))
x_values[0:10]

Number of points: 100
Number of values per point: 4


array([[-0.39,  0.98,  0.6 , -0.97],
       [ 0.35,  0.14,  0.61, -0.27],
       [-0.65,  0.56, -0.33, -0.66],
       [-0.73, -0.79, -0.43,  0.16],
       [-0.5 , -0.75,  0.33, -0.77],
       [-0.33, -0.55,  0.98,  0.34],
       [-0.64, -0.33,  0.23,  0.5 ],
       [ 0.59, -0.47,  0.82, -0.16],
       [ 0.38, -0.21, -0.61,  0.48],
       [ 0.96, -0.54,  0.22,  0.26]])

In [11]:
# compute function values in parallel

def compute_poly(poly, x_values):
    y_values = np.array([float(poly.eval(tuple(x))) for x in x_values])
    return x_values, y_values
    
parallel = Parallel(n_jobs=n_jobs, backend='loky')    
result_parallel = parallel(delayed(compute_poly)(poly, x_values) for poly in tqdm(polynomials_poly))

# dimension: [Polynomial: [x:[4], y]]
x_y_data = result_parallel

x_data = [poly[0] for poly in x_y_data]
y_data = [poly[1] for poly in x_y_data]

del parallel, result_parallel

In [12]:
# inspect first polynomial of x_y_data
print(len(x_y_data[0]))
print(len(x_y_data[0][0]))
print(len(x_y_data[0][1]))
x_y_data[0]

2
100
100


(array([[-0.39,  0.98,  0.6 , -0.97],
        [ 0.35,  0.14,  0.61, -0.27],
        [-0.65,  0.56, -0.33, -0.66],
        [-0.73, -0.79, -0.43,  0.16],
        [-0.5 , -0.75,  0.33, -0.77],
        [-0.33, -0.55,  0.98,  0.34],
        [-0.64, -0.33,  0.23,  0.5 ],
        [ 0.59, -0.47,  0.82, -0.16],
        [ 0.38, -0.21, -0.61,  0.48],
        [ 0.96, -0.54,  0.22,  0.26],
        [ 0.17, -0.66,  0.74, -0.53],
        [-0.75, -0.72,  0.86, -0.86],
        [ 0.98, -0.2 ,  0.  ,  0.35],
        [-0.6 ,  0.28,  0.59, -0.98],
        [ 0.6 , -0.21, -0.73,  0.88],
        [ 0.84, -0.43, -0.77,  0.22],
        [-0.01, -0.03, -0.27, -0.51],
        [ 0.53,  0.76,  0.99, -0.89],
        [ 0.69,  0.28,  0.7 , -0.54],
        [ 0.88,  0.54, -0.19, -0.37],
        [ 0.77,  0.77, -0.25,  0.69],
        [ 0.7 ,  0.16,  0.08,  0.76],
        [-0.21,  0.3 ,  0.9 , -0.89],
        [-0.92,  0.76,  0.21,  0.16],
        [ 0.8 , -0.55, -0.38, -0.89],
        [ 0.91, -0.15,  0.67,  0.04],
        [-0.

In [13]:
# inspect first polynomial of x_data
print(len(x_data[0]))
x_data[0]

100


array([[-0.39,  0.98,  0.6 , -0.97],
       [ 0.35,  0.14,  0.61, -0.27],
       [-0.65,  0.56, -0.33, -0.66],
       [-0.73, -0.79, -0.43,  0.16],
       [-0.5 , -0.75,  0.33, -0.77],
       [-0.33, -0.55,  0.98,  0.34],
       [-0.64, -0.33,  0.23,  0.5 ],
       [ 0.59, -0.47,  0.82, -0.16],
       [ 0.38, -0.21, -0.61,  0.48],
       [ 0.96, -0.54,  0.22,  0.26],
       [ 0.17, -0.66,  0.74, -0.53],
       [-0.75, -0.72,  0.86, -0.86],
       [ 0.98, -0.2 ,  0.  ,  0.35],
       [-0.6 ,  0.28,  0.59, -0.98],
       [ 0.6 , -0.21, -0.73,  0.88],
       [ 0.84, -0.43, -0.77,  0.22],
       [-0.01, -0.03, -0.27, -0.51],
       [ 0.53,  0.76,  0.99, -0.89],
       [ 0.69,  0.28,  0.7 , -0.54],
       [ 0.88,  0.54, -0.19, -0.37],
       [ 0.77,  0.77, -0.25,  0.69],
       [ 0.7 ,  0.16,  0.08,  0.76],
       [-0.21,  0.3 ,  0.9 , -0.89],
       [-0.92,  0.76,  0.21,  0.16],
       [ 0.8 , -0.55, -0.38, -0.89],
       [ 0.91, -0.15,  0.67,  0.04],
       [-0.78, -0.2 ,  0.43, -0.18],
 

In [14]:
# inspect first polynomial of y_data
print(len(y_data[0]))
y_data[0]

100


array([ 6.54669640e+00,  1.41552117e+01,  6.23861060e+00, -5.15635380e+00,
       -3.08100100e-01,  1.42110167e+01,  2.70513670e+00,  9.84773650e+00,
        1.33632263e+01, -3.70528080e+00,  6.87992220e+00,  2.14311290e+01,
        5.54864240e+00,  1.02749953e+01,  1.44934895e+01,  1.20238791e+01,
        4.75834720e+00,  3.60919691e+01,  2.16437686e+01,  1.46957146e+01,
        1.40337630e+01,  7.48636000e+00,  2.01434354e+01,  2.24756171e+01,
        2.41455830e+00,  1.01207996e+01,  8.08539430e+00,  1.73275651e+01,
        4.84143540e+00,  1.38312942e+01,  1.00359621e+01,  8.56234640e+00,
        1.12321440e+01,  8.34499840e+00,  8.26664000e+00,  1.49745371e+01,
        1.96612157e+01,  9.59123960e+00,  1.15108923e+01,  1.26079121e+01,
        3.18877648e+01,  1.90505869e+01,  5.10194450e+00,  2.13153018e+01,
        1.03172595e+01,  1.72387127e+01,  1.20904572e+01,  2.27792788e+01,
       -2.81260450e+00,  1.94617989e+01, -4.78808120e+00,  8.18009060e+00,
        1.09686977e+01,  

## 5: Data Export

In [15]:
# Csv exports
path_polynomials_df = './data/saved_polynomial_lists/polynomials_df' + str(interpretation_dataset_size) + '_variables_' + str(n) +  '_degree_' + str(d) + '_sparsity_' + str(sparsity) + '_astep_' + str(a_step)  + '_amin_' + str(a_min) + '_amax_' + str(a_max) + '.csv'
gh.export_csv(polynomials_df, path_polynomials_df)


# Pickle exports
path_polynomials_poly = './data/saved_polynomial_lists/polynomials_poly' + str(interpretation_dataset_size) + '_train_' + str(lambda_dataset_size) + '_variables_' + str(n) + '_degree_' + str(d) + '_sparsity_' + str(sparsity) + '_astep_' + str(a_step) + '_amin_' + str(a_min) + '_amax_' + str(a_max) + '_xstep_' + str(x_step) + '_xmin_' + str(x_min) + '_xmax_' + str(x_max) + training_string + '.pkl'
gh.export_pickle(polynomials_poly, path_polynomials_poly)

path_x_data = './data/saved_polynomial_lists/x_data' + str(interpretation_dataset_size) + '_train_' + str(lambda_dataset_size) + '_variables_' + str(n) + '_degree_' + str(d) + '_sparsity_' + str(sparsity) + '_astep_' + str(a_step) + '_amin_' + str(a_min) + '_amax_' + str(a_max) + '_xstep_' + str(x_step) + '_xmin_' + str(x_min) + '_xmax_' + str(x_max) + training_string + '.pkl'
gh.export_pickle(x_data, path_x_data)

path_y_data = './data/saved_polynomial_lists/y_data' + str(interpretation_dataset_size) + '_train_' + str(lambda_dataset_size) + '_variables_' + str(n) + '_degree_' + str(d) + '_sparsity_' + str(sparsity) + '_astep_' + str(a_step) + '_amin_' + str(a_min) + '_amax_' + str(a_max) + '_xstep_' + str(x_step) + '_xmin_' + str(x_min) + '_xmax_' + str(x_max) + training_string + '.pkl'
gh.export_pickle(y_data, path_y_data)
